/* DCC v32 — built-in Disney planner: map + live waits + time + park close + hotel + transport */
const dccV32ScheduleCache=new Map();
const dccV32HotelByDay=day=>day<='2026-11-28'?{name:'Wyndham Grand Orlando Resort Bonnet Creek',lat:28.3609,lon:-81.5272,type:'offsite'}:{name:"Disney's Saratoga Springs Resort & Spa",lat:28.3767,lon:-81.5202,type:'disney'};
function dccV32Norm(s){return(typeof dccNorm==='function'?dccNorm(s):String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim())}
function dccV32TimeText(v){if(!v)return'—';try{return new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZone:'America/New_York'})}catch(e){return'—'}}
function dccV32DayIsNow(day){try{return easternKey(new Date())===day}catch(e){return false}}
function dccV32NowMinutes(){let p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),o={};p.forEach(x=>o[x.type]=x.value);return (+o.hour%24)*60+(+o.minute)}
function dccV32AbsItems(items){let last=null,dayOff=0;return items.map((x,i)=>{let m=dccV30ParseTime(x[0]);if(m==null)return{index:i,item:x,abs:null};if(last!=null&&m+dayOff<last-360)dayOff+=1440;let abs=m+dayOff;last=abs;return{index:i,item:x,abs}})}
function dccV32FmtAbs(m){if(m==null)return'—';return fmt(dccV30Clock(m%1440))+(m>=1440?' next day':'')}
async function dccV32ParkHours(pk,day){if(!pk)return null;let k=pk+'|'+day;if(dccV32ScheduleCache.has(k))return dccV32ScheduleCache.get(k);let p=(async()=>{try{let [y,m]=day.split('-'),r=await fetch('https://api.themeparks.wiki/v1/entity/'+P[pk].id+'/schedule?year='+y+'&month='+Number(m),{cache:'no-store'});if(!r.ok)return null;let j=await r.json(),rows=Array.isArray(j)?j:(j.schedule||j.schedules||[]),same=rows.filter(x=>String(x.date||'').slice(0,10)===day),ops=same.filter(x=>!x.type||/OPERATING|TICKETED_EVENT/i.test(x.type));let use=ops.length?ops:same;if(!use.length)return null;let open=use.map(x=>x.openingTime||x.open||x.startTime).filter(Boolean).sort()[0],close=use.map(x=>x.closingTime||x.close||x.endTime).filter(Boolean).sort().slice(-1)[0];return{open,close,rows:use}}catch(e){return null}})();dccV32ScheduleCache.set(k,p);return p}
function dccV32FallbackClose(day){let a=dccV32AbsItems(itinerary[day]?.items||[]),hit=[...a].reverse().find(x=>x.abs!=null&&/(exit|ends|party)/i.test(x.item[2]||''));return hit?hit.abs:null}
function dccV32ClosestPark(point,day){let keys=dayParkKeys?.[day]?.length?dayParkKeys[day]:Object.keys(P);if(!keys.length)return null;if(!point)return keys[0];return keys.map(pk=>({pk,d:miles(point,{lat:P[pk].c[0],lon:P[pk].c[1]})})).sort((a,b)=>a.d-b.d)[0].pk}
function dccV32BestTextMatch(q,candidates){let n=dccV32Norm(q),qt=n.split(' ').filter(x=>x.length>2),best=null,bs=0;for(const c of candidates){let cn=dccV32Norm(c.name),ct=cn.split(' ').filter(x=>x.length>2),same=qt.filter(x=>ct.includes(x)).length,score=ct.length?same/ct.length:0;if(n.includes(cn)&&cn.length>3)score=Math.max(score,1);if(cn.includes(n)&&n.length>4)score=Math.max(score,.85);if(score>bs){bs=score;best=c}}return bs>=.34?best:null}
async function dccV32GpsIfTripDay(day){if(!dccV32DayIsNow(day)||!navigator.geolocation)return null;return new Promise(ok=>navigator.geolocation.getCurrentPosition(p=>ok({name:'Your current location',lat:p.coords.latitude,lon:p.coords.longitude,source:'GPS',index:-1}),()=>ok(null),{enableHighAccuracy:true,timeout:4500,maximumAge:45000}))}
function dccV32AnchorFromPlan(day,q,pts){let explicit=dccV32BestTextMatch(q,pts);if(explicit&&/(after|near|from|at|leaving|leave)/i.test(q))return explicit;let abs=dccV32AbsItems(itinerary[day].items),now=dccV32DayIsNow(day)?dccV32NowMinutes():null;if(now!=null){let done=abs.filter(x=>x.abs!=null&&x.abs<=now).slice(-1)[0],p=done&&pts.find(z=>z.index===done.index);if(p)return p;let next=abs.find(x=>x.abs!=null&&x.abs>now),np=next&&pts.find(z=>z.index===next.index);if(np)return np}let firstFlex=itinerary[day].items.findIndex(x=>!x[0]),prior=[];for(let i=0;i<(firstFlex<0?itinerary[day].items.length:firstFlex);i++){let p=pts.find(z=>z.index===i);if(p)prior.push(p)}return prior.slice(-1)[0]||pts[0]||null}
function dccV32NextFixed(day,anchorIndex){let abs=dccV32AbsItems(itinerary[day].items),now=dccV32DayIsNow(day)?dccV32NowMinutes():null;if(now!=null){let x=abs.find(z=>z.abs!=null&&z.abs>now);return x||null}return abs.find(z=>z.abs!=null&&z.index>Math.max(-1,anchorIndex))||null}
async function dccV32Context(day,q){let pts=[];try{pts=await resolveDayPoints(day)}catch(e){}let gps=await dccV32GpsIfTripDay(day),plan=dccV32AnchorFromPlan(day,q,pts),where=gps||plan,pk=dccV32ClosestPark(where,day),hours=await dccV32ParkHours(pk,day),next=dccV32NextFixed(day,plan?.index??-1),nextPoint=next?pts.find(x=>x.index===next.index):null,hotel=dccV32HotelByDay(day);return{day,q,pts,gps,where,plan,pk,hours,next,nextPoint,hotel,isNow:dccV32DayIsNow(day)}}
function dccV32CloseLabel(ctx){if(ctx.hours?.close)return dccV32TimeText(ctx.hours.close);let m=dccV32FallbackClose(ctx.day);return m==null?'not loaded':dccV32FmtAbs(m)}
function dccV32AvailMinutes(ctx){if(!ctx.isNow)return null;let now=dccV32NowMinutes(),limits=[];if(ctx.next?.abs!=null){let x=ctx.next.abs;while(x<now)x+=1440;limits.push(x-now)}if(ctx.hours?.close){let x=new Date(ctx.hours.close),n=new Date(),d=(x-n)/60000;if(Number.isFinite(d)&&d>0)limits.push(d)}return limits.length?Math.min(...limits):null}
function dccV32Meta(ctx){let loc=ctx.gps?'GPS':ctx.where?.name||'itinerary location',park=ctx.pk?P[ctx.pk].n:'resort / travel day',next=ctx.next?dccV32FmtAbs(ctx.next.abs)+' '+ctx.next.item[2]:'no fixed item ahead',mode=ctx.isNow?'LIVE NOW':'PLANNING PREVIEW';return'<div class="dccPlannerContext"><b>'+mode+'</b><span>📍 '+dccEsc(loc)+'</span><span>🏰 '+dccEsc(park)+'</span><span>🕘 Close: '+dccEsc(dccV32CloseLabel(ctx))+'</span><span>⏭ '+dccEsc(next)+'</span><span>🏨 '+dccEsc(ctx.hotel.name)+'</span></div>'}
function dccV32Cards(title,intro,opts,ctx,foot=''){let cards=opts.slice(0,3).map((o,i)=>'<div class="dccPlannerOption"><div class="dccPlannerRank">'+(i+1)+'</div><div class="dccPlannerOptionBody"><b>'+dccEsc(o.title)+'</b>'+(o.meta?'<span class="dccPlannerOptionMeta">'+dccEsc(o.meta)+'</span>':'')+'<small>'+dccEsc(o.why)+'</small></div></div>').join('');return dccV32Meta(ctx)+'<div class="dccPlannerAnswer"><h4>'+dccEsc(title)+'</h4><p>'+dccEsc(intro)+'</p>'+cards+(foot?'<div class="dccPlannerFoot">'+dccEsc(foot)+'</div>':'')+'</div>'}
async function dccV32LiveRides(ctx){if(!ctx.pk)return[];try{let j=await dccGetLive(ctx.pk);return(j.liveData||[]).filter(x=>x.entityType==='ATTRACTION'&&x.status==='OPERATING'&&x.location&&Number.isFinite(x.location.latitude)).map(x=>{let q=x.queue||{},w=q.STANDBY&&Number.isFinite(q.STANDBY.waitTime)?q.STANDBY.waitTime:null;return{name:x.name,lat:x.location.latitude,lon:x.location.longitude,wait:w,status:x.status}})}catch(e){return[]}}
function dccV32PlannedPriority(day,name){let n=canonName(name);return itinerary[day].items.some(x=>canonName(x[2])===n)}
async function dccV32RideAnswer(ctx){let rides=await dccV32LiveRides(ctx),avail=dccV32AvailMinutes(ctx),where=ctx.where||{lat:P[ctx.pk].c[0],lon:P[ctx.pk].c[1]},next=ctx.nextPoint;let scored=rides.map(r=>{let d=miles(where,r),walk=dccEstimateWalk?dccEstimateWalk(d):Math.max(4,Math.round(d*25)),wait=r.wait==null?22:r.wait,back=next?miles(r,next)*8:0,priority=dccV32PlannedPriority(ctx.day,r.name)?-13:3,total=walk+wait+12,score=wait+walk*1.35+back+priority;return{...r,walk,total,score,fit:avail==null||total<avail-8,planned:dccV32PlannedPriority(ctx.day,r.name)}}).filter(x=>x.fit).sort((a,b)=>a.score-b.score);let opts=scored.slice(0,3).map(x=>({title:x.name,meta:(x.wait==null?'wait not posted':x.wait+' min wait')+' • ~'+x.walk+' min walk'+(x.planned?' • on your plan':''),why:(x.planned?'This is already one of your priorities. ':'')+'It scores well for current wait + walking distance'+(next?' and keeps you positioned for '+next.name+'.':'.')}));let foot=ctx.isNow?'Waits are live and refreshed about every 5 minutes.':'Current wait data is only a planning snapshot today — it is not a forecast for your trip date.';return dccV32Cards('Best ride next','I ranked operating rides by posted wait, walking from your location, your planned priorities, the next fixed event, and backtracking.',opts,ctx,foot)}
async function dccV32Restaurants(ctx){if(!ctx.pk)return[];try{let c=await dccGetChildren(ctx.pk);return c.filter(x=>x.entityType==='RESTAURANT'&&x.location&&Number.isFinite(x.location.latitude)).map(x=>({name:x.name,lat:x.location.latitude,lon:x.location.longitude}))}catch(e){return[]}}
async function dccV32FoodAnswer(ctx){let rows=await dccV32Restaurants(ctx),where=ctx.where||{lat:P[ctx.pk].c[0],lon:P[ctx.pk].c[1]},next=ctx.nextPoint,planned=ctx.pts.filter(p=>/restaurant|dinner|lunch|breakfast|brunch|cake bake|brown derby|yak yeti|via napoli|le cellier|turf club/i.test(p.name));for(const p of planned)if(!rows.some(x=>canonName(x.name)===canonName(p.name)))rows.push({name:p.name,lat:p.lat,lon:p.lon,planned:true});let scored=rows.map(r=>{let d=miles(where,r),walk=Math.max(3,Math.round(d*22+3)),flow=next?miles(r,next)*7:0,plannedHit=planned.some(p=>canonName(p.name)===canonName(r.name));return{...r,walk,score:walk+flow-(plannedHit?12:0),planned:plannedHit}}).sort((a,b)=>a.score-b.score).slice(0,3),opts=scored.map(x=>({title:x.name,meta:'~'+x.walk+' min walk'+(x.planned?' • already in your plan':''),why:(x.planned?'This matches a dining stop you already considered. ':'')+'It minimizes extra walking'+(next?' and keeps the route moving toward '+next.name+'.':'.')}));if(!opts.length&&planned.length)opts=planned.slice(0,3).map(x=>({title:x.name,meta:'planned dining option',why:'This is already part of this day and can be timed around the surrounding stops.'}));return dccV32Cards('Where to eat','I’m prioritizing location and itinerary flow first so lunch or dinner does not send you across the park and back.',opts,ctx,'Restaurant hours, menus, and same-day dining availability can change; verify those when choosing.')}
async function dccV32CharactersAnswer(ctx){if(!ctx.pk)return dccV32Cards('Nearby characters','This day is not currently tied to a theme park.',[],ctx);let rows=[];try{rows=await dccCharacterRows(ctx.pk)}catch(e){}let where=ctx.where||{lat:P[ctx.pk].c[0],lon:P[ctx.pk].c[1]},a=rows.map(x=>{let st=typeof dccV27CharacterState==='function'?dccV27CharacterState(x):{kind:'location',label:'LOCATION'},walk=Math.max(3,Math.round(miles(where,x)*22+3)),rank=st.kind==='now'?0:st.kind==='next'?20:40;return{...x,st,walk,score:rank+walk}}).sort((a,b)=>a.score-b.score).slice(0,3),opts=a.map(x=>({title:x.name,meta:x.st.label+' • ~'+x.walk+' min walk',why:(x.st.kind==='now'?'This meet appears scheduled/open now. ':x.st.kind==='next'?'This is an upcoming scheduled meet. ':'This is a confirmed character location. ')+'It is one of the closer options from your current/planned position.'}));return dccV32Cards('Nearby character meets','I ranked character locations by whether the meet is happening now/upcoming and how much walking it adds.',opts,ctx,'Character schedules can change during the day.')}
async function dccV32Destination(ctx){let rides=await dccV32LiveRides(ctx),cands=[...ctx.pts,...rides,...(dccTransportHubs||[]),ctx.hotel];let q=dccV32Norm(ctx.q);if(/hotel|resort|back/.test(q))return ctx.hotel;if(/there|next stop|next place|next item/.test(q)&&ctx.nextPoint)return ctx.nextPoint;return dccV32BestTextMatch(ctx.q,cands)}
function dccV32TravelChoices(ctx,a,b){let d=miles(a,b),base=legMode(ctx.day,a,b,d),n=dccV32Norm((a.name||'')+' '+(b.name||'')),opts=[];let add=(title,mins,why)=>{if(!opts.some(x=>x.title===title))opts.push({title,meta:mins?'~'+mins+' min':'timing varies',why})};if(d<1.4)add('Walk',Math.max(4,Math.round(d*22+3)),'Direct walking avoids waiting for transportation and follows the mapped pedestrian route where available.');if((/hollywood|boardwalk|yacht|beach|epcot/.test(n))&&d<3)add('Friendship Boat',Math.max(18,Math.round(d/3*60+10)),'Good foot-saving option if a boat is boarding soon; waiting can make walking faster.');if(/epcot/.test(n)&&/hollywood/.test(n))add('Skyliner',Math.max(20,Math.round(d/8*60+12)),'Usually a strong park-to-park option using International Gateway and the Skyliner connection.');if(ctx.hotel.type==='disney'&&(b===ctx.hotel||/saratoga/.test(dccV32Norm(b.name))))add('Disney bus',Math.max(25,Math.round(d/18*60+20)),'No rideshare cost; allow for walking to the bus loop plus waiting/loading time.');if(d>=1.2||b===ctx.hotel)add('Rideshare',Math.max(15,Math.round(d/24*60+10)),'Usually the quickest door-to-door choice when saving time or tired feet matters more than cost.');if(!opts.length)add(base.mode,base.mins,base.detail);return opts.slice(0,3)}
async function dccV32DirectionsAnswer(ctx){let dest=await dccV32Destination(ctx);if(!dest)return dccV32Cards('How to get there','Tell me the destination in the question — for example “How do we get to Slinky Dog Dash?” or “How do we get back to the hotel?”',[],ctx);let from=ctx.where||ctx.plan||ctx.pts[0];if(!from)return dccV32Cards('How to get there','I found the destination but I do not have a starting location for this day yet.',[],ctx);let opts=dccV32TravelChoices(ctx,from,dest);return dccV32Cards('How to get to '+dest.name,'I compared the mapped distance and the Disney transportation choices that make sense for this leg.',opts,ctx,'During the trip, GPS is used automatically when location permission is available.')}
function dccV32LeaveAnswer(ctx){let close=dccV32CloseLabel(ctx),hotel=ctx.hotel,planned=dccV32FallbackClose(ctx.day),opts=[];if(planned!=null)opts.push({title:'Follow the planned exit',meta:dccV32FmtAbs(planned),why:'This is already an anchor in your itinerary, so it protects the rest of the night and your trip back to '+hotel.name+'.'});if(hotel.type==='disney')opts.push({title:'Disney bus back to Saratoga',meta:'allow ~30–50 min including wait',why:'Best no-extra-cost option from the park; leave a buffer for walking to the bus loop, waiting and loading.'});else opts.push({title:'Rideshare back to Wyndham',meta:'allow pickup + drive buffer',why:'This is the straightforward option to an off-site hotel and avoids a Disney-transport transfer.'});opts.push({title:'Earlier low-stress exit',meta:'leave 30–45 min before your hard stop',why:'Best when everyone is tired or the next morning is important; it also avoids some end-of-night transportation pressure.'});return dccV32Cards('When to head back','Park close is '+close+'. I’m also using your hotel and the transportation required to get there.',opts,ctx,'On the actual day, the planner will use the current time and live location automatically.')}
async function dccV32WhatNow(ctx){let ride=await dccV32LiveRides(ctx),where=ctx.where||ctx.plan,opts=[];if(ctx.pk&&where&&ride.length){let scored=ride.map(r=>{let walk=Math.max(3,Math.round(miles(where,r)*22+3)),w=r.wait==null?22:r.wait;return{...r,walk,score:w+walk*1.3-(dccV32PlannedPriority(ctx.day,r.name)?10:0)}}).sort((a,b)=>a.score-b.score);for(const x of scored.slice(0,2))opts.push({title:x.name,meta:(x.wait==null?'wait not posted':x.wait+' min wait')+' • ~'+x.walk+' min walk',why:'Strong balance of low time cost, nearby location and your planned route.'})}let hour=dccV32NowMinutes()/60;if((ctx.isNow&&hour>=11&&hour<=14)||/lunch|eat|food/i.test(ctx.q)){let foods=await dccV32Restaurants(ctx);if(foods.length&&where){let f=foods.map(x=>({...x,walk:Math.max(3,Math.round(miles(where,x)*22+3))})).sort((a,b)=>a.walk-b.walk)[0];opts.push({title:'Take a food break at '+f.name,meta:'~'+f.walk+' min walk',why:'It is nearby and this is a reasonable meal window, which can reduce extra backtracking later.'})}}if(opts.length<3&&ctx.nextPoint)opts.push({title:'Start moving toward '+ctx.nextPoint.name,meta:ctx.next?dccV32FmtAbs(ctx.next.abs):'',why:'This protects the next fixed reservation/show instead of squeezing in something that could make you late.'});return dccV32Cards('What I would do next','I’m balancing live waits, your location, walking, the next fixed item, park close, and the trip back to your hotel.',opts,ctx,ctx.isNow?'This is using live conditions now.':'This is a planning preview; current waits are not a forecast for the trip date.')}
async function dccV32Answer(day,q){let ctx=await dccV32Context(day,q),n=dccV32Norm(q);if(/lunch|dinner|eat|food|restaurant|meal/.test(n))return dccV32FoodAnswer(ctx);if(/character|meet mickey|princess/.test(n))return dccV32CharactersAnswer(ctx);if(/how.*get|directions|route to|walk to|boat to|bus to|skyliner to|get back/.test(n))return dccV32DirectionsAnswer(ctx);if(/head back|leave.*park|back.*hotel|go.*hotel|park close|closes/.test(n))return dccV32LeaveAnswer(ctx);if(/ride.*next|next.*ride|best ride|which ride/.test(n))return dccV32RideAnswer(ctx);return dccV32WhatNow(ctx)}
async function dccV32AskBuiltIn(day){let ta=$('dccAskQuestion'),q=(ta?.value||'').trim();if(!q){dccV30PlannerMessage(day,'Type a question or tap one of the common questions.','warn');ta?.focus();return}localStorage.setItem(dccV30QKey(day),q);dccV30PlannerMessage(day,'Checking the itinerary, map, time, live park data and transportation…');try{let html=await dccV32Answer(day,q),x=$('dccPlannerResult');if(x){x.className='dccPlannerResult plannerBuiltIn';x.innerHTML=html}}catch(e){dccV30PlannerMessage(day,'I could not load enough planning data for that question. Try again or make the question more specific.','warn')}}
/* Replace the old external-window behavior with the built-in planner. */
dccV30AskChatGPT=dccV32AskBuiltIn;
function dccV32EnhancePlanner(day){let box=$('dccPlannerTools');if(!box||box.dataset.v32)return;box.dataset.v32='1';let head=box.querySelector('.dccPlannerHead b');if(head)head.textContent='✨ Disney Travel Planner';let sub=box.querySelector('.dccPlannerHead small');if(sub)sub.textContent='Built in: uses your itinerary, mapped location, time, live waits, park hours, hotel and transportation.';let ta=$('dccAskQuestion');if(ta)ta.placeholder='Ask: Where should we have lunch? What ride should we do next? How do we get to Slinky Dog?';let common=document.createElement('div');common.className='dccCommonQuestions';common.innerHTML='<button data-dcc-q="What should we do next?">✨ What next?</button><button data-dcc-q="What ride should we do next?">🎢 Best ride</button><button data-dcc-q="Where should we have lunch?">🍽️ Lunch</button><button data-dcc-q="How do we get to the next stop?">🧭 Get there</button><button data-dcc-q="When should we head back to the hotel?">🏨 Head back</button><button data-dcc-q="What character meets are nearby?">★ Characters</button>';ta?.insertAdjacentElement('afterend',common);common.onclick=e=>{let b=e.target.closest('[data-dcc-q]');if(!b)return;ta.value=b.dataset.dccQ;localStorage.setItem(dccV30QKey(day),ta.value);dccV32AskBuiltIn(day)};let ask=$('dccAskBtn');if(ask){ask.textContent='✨ Ask Disney Planner';ask.onclick=()=>dccV32AskBuiltIn(day)}let result=$('dccPlannerResult');if(result)result.innerHTML='Ask a question above. During the trip, the planner will automatically use GPS when available; before the trip it uses the matching itinerary stop as your planning location.'}
const dccV32BaseDayPanel=dayPanel;dayPanel=function(day){dccV32BaseDayPanel(day);setTimeout(()=>dccV32EnhancePlanner(day),0)};
