/* DCC v37 — location-aware Disney Quick Find above Smart Trip Plan */
(()=>{
 const qState={lastQuery:'',lastLocation:null,lastSource:'',lastResults:[]};
 const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rad=x=>x*Math.PI/180;
 function miles(a,b){let R=3958.8,dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon),la1=rad(a.lat),la2=rad(b.lat);let h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
 function walkMin(mi){return Math.max(2,Math.round(mi*21))}
 function inWDW(p){return p&&p.lat>28.30&&p.lat<28.46&&p.lon>-81.66&&p.lon<-81.45}
 function dateKey(){try{return new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch(e){return new Date().toISOString().slice(0,10)}}
 function plannedDay(){let k=dateKey();if(itinerary[k])return k;let days=Object.keys(itinerary).sort(),now=k;return days.find(d=>d>=now)||days[0]}
 async function plannedAnchor(){let day=plannedDay();try{let pts=await resolveDayPoints(day);if(pts&&pts.length)return{lat:pts[0].lat,lon:pts[0].lon,name:pts[0].name,day}}catch(e){}let p=P[day==='2026-11-30'?'ak':day==='2026-12-02'||day==='2026-12-03'?'ep':day==='2026-11-28'?'hs':'mk'];return{lat:p.c[0],lon:p.c[1],name:p.n,day}}
 function gps(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS unavailable'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:8500,maximumAge:45000})})}
 async function getOrigin(){try{let p=await gps();if(inWDW(p)){qState.lastLocation=p;qState.lastSource='Your iPhone GPS';return p}let a=await plannedAnchor();qState.lastLocation=a;qState.lastSource='Planned Disney location (GPS is off-property)';return a}catch(e){let a=await plannedAnchor();qState.lastLocation=a;qState.lastSource='Planned Disney location (GPS unavailable)';return a}}
 function nearestPark(origin){let rows=Object.entries(P).map(([pk,p])=>({pk,d:miles(origin,{lat:p.c[0],lon:p.c[1]})})).sort((a,b)=>a.d-b.d);return rows[0]}
 function queryType(q){q=q.toLowerCase();if(/bath|restroom|toilet|potty/.test(q))return'toilets';if(/lunch|dinner|breakfast|food|restaurant|eat|snack|coffee|drink/.test(q))return'food';if(/character|mickey|princess|meet/.test(q))return'characters';if(/bus|boat|skyliner|monorail|transport|station|dock/.test(q))return'transport';if(/ride|attraction|roller|coaster|something fun|what next/.test(q))return'rides';return'nearby'}
 function qualifier(q){q=q.toLowerCase();return{thrill:/thrill|coaster|fast|scary/.test(q),kids:/kid|girl|family|easy|little/.test(q),quick:/quick|fast|short|near/.test(q)} }
 async function overpass(origin,type){let radius=2800,filter=type==='toilets'?'["amenity"="toilets"]':'["amenity"~"restaurant|fast_food|cafe|food_court|ice_cream"]';let query='[out:json][timeout:15];(node(around:'+radius+','+origin.lat+','+origin.lon+')'+filter+';way(around:'+radius+','+origin.lat+','+origin.lon+')'+filter+';relation(around:'+radius+','+origin.lat+','+origin.lon+')'+filter+';);out center tags;';let r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(query),{cache:'no-store'});if(!r.ok)throw new Error('Nearby place lookup failed');let j=await r.json(),rows=[];for(const e of j.elements||[]){let lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;let t=e.tags||{},name=t.name||(type==='toilets'?'Guest Restroom':'Dining location');if(type==='food'&&!t.name)continue;let d=miles(origin,{lat,lon});rows.push({type,name,lat,lon,d,tags:t})}let seen=new Set();return rows.filter(x=>{let k=(x.name+'|'+x.lat.toFixed(4)+'|'+x.lon.toFixed(4)).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.d-b.d)}
 async function rideRows(origin,q){let near=nearestPark(origin),pks=near.d<1.4?[near.pk]:Object.keys(P),all=[],qual=qualifier(q);for(const pk of pks){let j=await dccGetLive(pk);for(const x of j.liveData||[]){if(x.entityType!=='ATTRACTION'||!x.location||!Number.isFinite(x.location.latitude))continue;let lat=x.location.latitude,lon=x.location.longitude,d=miles(origin,{lat,lon}),stand=x.queue?.STANDBY?.waitTime,w=Number.isFinite(stand)?stand:null,n=(x.name||'').toLowerCase();if(qual.thrill&&!/(mountain|coaster|mine train|everest|flight of passage|slinky|test track|guardians|resistance|tower|rock)/.test(n))continue;if(qual.kids&&/(tower|rock|everest|flight of passage)/.test(n))continue;let travel=walkMin(d),score=travel+(w??30)+(x.status==='OPERATING'?0:999);all.push({type:'ride',name:x.name,lat,lon,d,travel,wait:w,status:x.status,park:P[pk].n,score})}}return all.sort((a,b)=>a.score-b.score)}
 async function characterRows(origin){let near=nearestPark(origin),pks=near.d<1.4?[near.pk]:Object.keys(P),rows=[];for(const pk of pks){for(const x of await dccCharacterRows(pk)){let d=miles(origin,{lat:x.lat,lon:x.lon}),state=typeof dccV27CharacterState==='function'?dccV27CharacterState(x):null;rows.push({type:'character',name:x.name,venue:x.venue,lat:x.lat,lon:x.lon,d,park:P[pk].n,state})}}return rows.sort((a,b)=>a.d-b.d)}
 async function transportRows(origin){let src=[...(window.dccTransportHubs||[]),...(window.dccSaratogaPoints||[])],rows=[];for(const x of src){if(!Number.isFinite(x.lat))continue;let lon=x.lon??x.long,d=miles(origin,{lat:x.lat,lon});rows.push({type:'transport',name:x.name,kind:x.kind,lat:x.lat,lon,d,note:x.note||''})}return rows.sort((a,b)=>a.d-b.d)}
 function reason(x,i){if(x.type==='ride'){let wait=x.wait==null?'wait not posted':x.wait+' min wait',fit=x.status==='OPERATING'?'operating now':String(x.status||'status unknown').replaceAll('_',' ');return(i===0?'Best total time from where you are. ':'')+x.travel+' min estimated walk • '+wait+' • '+fit+'.'}if(x.type==='food')return(i===0?'Closest useful dining option from your position. ':'')+walkMin(x.d)+' min estimated walk • '+(x.tags?.cuisine?x.tags.cuisine.replaceAll(';',', ')+' • ':'')+(x.tags?.amenity==='fast_food'?'quick-service style':'dining location')+'.';if(x.type==='toilets')return(i===0?'Closest mapped restroom. ':'')+walkMin(x.d)+' min estimated walk • '+Math.max(0.1,x.d).toFixed(2)+' mi away.';if(x.type==='character')return(i===0?'Closest character option. ':'')+walkMin(x.d)+' min estimated walk'+(x.state?' • '+x.state.detail:'')+'.';if(x.type==='transport')return(i===0?'Closest transportation point. ':'')+walkMin(x.d)+' min estimated walk • '+(x.note||x.kind||'Disney transport')+'.';return walkMin(x.d)+' min estimated walk.'}
 function dir(x){return'https://maps.apple.com/?daddr='+encodeURIComponent(x.lat+','+x.lon)+'&dirflg=w'}
 function resultCard(x,i){let meta=x.type==='ride'?'<span>'+esc(x.park||'')+'</span><span>'+(x.wait==null?'Wait —':esc(x.wait+' min wait'))+'</span>':x.type==='character'?'<span>'+esc(x.park||'')+'</span><span>'+esc(x.state?.label||'Character')+'</span>':'<span>'+walkMin(x.d)+' min walk</span><span>'+Math.max(.1,x.d).toFixed(2)+' mi</span>';return'<article class="dccFinderResult"><div class="dccFinderRank">'+(i+1)+'</div><div class="dccFinderResultBody"><h3>'+esc(x.name)+'</h3><div class="dccFinderMeta">'+meta+'</div><p>'+esc(reason(x,i))+'</p><div class="dccFinderActions"><a target="_blank" rel="noopener" href="'+dir(x)+'">🚶 Walk there</a><button type="button" data-find-map="'+i+'">🗺️ Show on map</button></div></div></article>'}
 function status(msg,kind=''){let e=document.getElementById('dccFinderStatus');if(e){e.className='dccFinderStatus '+kind;e.innerHTML=msg}}
 function showResults(rows,q){qState.lastResults=rows.slice(0,3);let out=document.getElementById('dccFinderResults');if(!out)return;if(!rows.length){out.innerHTML='<div class="dccFinderEmpty">I couldn’t find a strong nearby match. Try a broader request like <b>ride</b>, <b>lunch</b>, <b>bathroom</b>, <b>character</b>, or <b>transportation</b>.</div>';return}out.innerHTML=rows.slice(0,3).map(resultCard).join('');out.querySelectorAll('[data-find-map]').forEach(b=>b.onclick=()=>showOnMap(Number(b.dataset.findMap)));status('Using <b>'+esc(qState.lastSource)+'</b> • showing the best '+Math.min(3,rows.length)+' options for “'+esc(q)+'”.','ok')}
 async function search(q){q=(q||'').trim();if(!q)return;let btn=document.getElementById('dccFinderGo');btn&&(btn.disabled=true);qState.lastQuery=q;status('📍 Checking your location and nearby Disney options…','busy');try{let origin=await getOrigin(),type=queryType(q),rows=[];if(type==='rides')rows=await rideRows(origin,q);else if(type==='characters')rows=await characterRows(origin);else if(type==='transport')rows=await transportRows(origin);else if(type==='food'||type==='toilets')rows=await overpass(origin,type);else{let [r,f]=await Promise.all([rideRows(origin,q),overpass(origin,'food').catch(()=>[])]);rows=[...r.slice(0,2),...f.slice(0,2)].sort((a,b)=>(a.score??walkMin(a.d))-(b.score??walkMin(b.d)))}showResults(rows,q)}catch(e){status('I couldn’t complete that nearby search. Check Location permission and try again.','warn')}finally{btn&&(btn.disabled=false)}}
 async function showOnMap(i){let x=qState.lastResults[i];if(!x)return;openShell();$('mapview').classList.remove('liveMode');$('tabs').style.display='none';$('maptitle').textContent=x.name;await ensureMainMap();layer.clearLayers();routeLayer.clearLayers();let o=qState.lastLocation;if(o&&Number.isFinite(o.lat))L.marker([o.lat,o.lon]).addTo(layer).bindPopup('<b>Your planning position</b><br><small>'+esc(qState.lastSource)+'</small>');L.marker([x.lat,x.lon]).addTo(layer).bindPopup('<b>'+esc(x.name)+'</b><br><small>'+esc(reason(x,0))+'</small>').openPopup();if(o&&Number.isFinite(o.lat)){let line=await brouterProfileLine(o,x,'trekking').catch(()=>null);if(line)L.polyline(line,{color:'#0b63ce',weight:5,opacity:.9}).addTo(routeLayer);map.fitBounds([[o.lat,o.lon],[x.lat,x.lon]],{padding:[35,35]})}else map.setView([x.lat,x.lon],16);$('routeSummary').innerHTML='<div class="parkPlanKey"><b>📍 '+esc(x.name)+'</b><small>'+esc(reason(x,0))+'</small></div>';$('waittitle').textContent='Quick Find recommendation';$('waitupdated').textContent='Location-aware';$('waitlist').innerHTML='<div class="dccFinderMapNote"><a target="_blank" rel="noopener" href="'+dir(x)+'">Open walking directions in Apple Maps ›</a></div>';setTimeout(()=>map.invalidateSize(false),60)}
 function mount(){if(document.getElementById('dccQuickFinder'))return;let cards=[...document.querySelectorAll('.content>.card')],smart=cards.find(c=>c.querySelector('h2')?.textContent?.includes('Smart Trip Plan'));if(!smart)return;let sec=document.createElement('section');sec.id='dccQuickFinder';sec.className='card dccQuickFinder';sec.innerHTML='<div class="head"><h2>✨ Disney Quick Find</h2><span class="updated">Location-aware</span></div><p class="dccFinderIntro">Tell me what you need and I’ll use your location, live ride waits, Disney map data and nearby park places to give you the best 1–3 options.</p><div class="dccFinderSearch"><input id="dccFinderInput" type="search" autocomplete="off" placeholder="I need lunch, a ride, a bathroom…"><button id="dccFinderGo" type="button">Find</button></div><div class="dccFinderChips"><button data-q="I need a bathroom">🚻 Bathroom</button><button data-q="Where should we have lunch?">🍔 Lunch</button><button data-q="What ride should we do next?">🎢 Ride</button><button data-q="Where can we meet a character?">★ Character</button><button data-q="What transportation is closest?">🚌 Transport</button></div><div id="dccFinderStatus" class="dccFinderStatus">GPS is used only when you search. If you’re not on Disney property yet, the app previews from your planned Disney location.</div><div id="dccFinderResults" class="dccFinderResults"></div>';smart.parentNode.insertBefore(sec,smart);let input=sec.querySelector('#dccFinderInput');sec.querySelector('#dccFinderGo').onclick=()=>search(input.value);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();search(input.value)}};sec.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{input.value=b.dataset.q;search(b.dataset.q)})}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();setTimeout(mount,100);
})();
