/* DCC v31 — optimize FLEX ride order by mapped walking paths before assigning times */
const dccV31BaseRecommendFlex=dccV30RecommendFlex;
function dccV31OriginalFlexName(day,name){let a=dccOriginalItems?.[day]||[];return a.some(x=>x[2]===name&&!x[0])}
function dccV31PathMiles(line){if(!line||line.length<2)return null;let t=0;for(let i=0;i<line.length-1;i++)t+=miles({lat:line[i][0],lon:line[i][1]},{lat:line[i+1][0],lon:line[i+1][1]});return t}
async function dccV31WalkDistance(a,b,cache){if(!a||!b)return 0;let ka=(a.name||'')+'@'+a.lat.toFixed(5)+','+a.lon.toFixed(5),kb=(b.name||'')+'@'+b.lat.toFixed(5)+','+b.lon.toFixed(5),key=ka<kb?ka+'|'+kb:kb+'|'+ka;if(cache.has(key))return cache.get(key);let p=(async()=>{try{let line=await brouterProfileLine(a,b,'trekking'),d=dccV31PathMiles(line);if(Number.isFinite(d)&&d>0)return d}catch(e){}return miles(a,b)*1.25})();cache.set(key,p);return p}
function dccV31Permute(arr){let out=[];function go(prefix,rest){if(!rest.length){out.push(prefix);return}for(let i=0;i<rest.length;i++)go(prefix.concat(rest[i]),rest.slice(0,i).concat(rest.slice(i+1)))}go([],arr);return out}
async function dccV31BestOrder(entries,startAnchor,endAnchor,cache){if(entries.length<2)return entries;let nodes=[...entries];let pairs=[];let all=[...(startAnchor?[startAnchor]:[]),...nodes,...(endAnchor?[endAnchor]:[])];for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)pairs.push(dccV31WalkDistance(all[i],all[j],cache));await Promise.all(pairs);
 const dist=(a,b)=>dccV31WalkDistance(a,b,cache);
 if(nodes.length<=7){let perms=dccV31Permute(nodes),best=nodes,bestScore=Infinity;for(const p of perms){let score=0;if(startAnchor)score+=await dist(startAnchor,p[0]);for(let i=0;i<p.length-1;i++)score+=await dist(p[i],p[i+1]);if(endAnchor)score+=await dist(p[p.length-1],endAnchor);if(score<bestScore){bestScore=score;best=p}}return best}
 let remaining=[...nodes],ordered=[],cur=startAnchor||remaining.shift();if(!startAnchor)ordered.push(cur);while(remaining.length){let scored=await Promise.all(remaining.map(async x=>({x,d:await dist(cur,x)})));scored.sort((a,b)=>a.d-b.d);let next=scored[0].x;ordered.push(next);remaining=remaining.filter(x=>x!==next);cur=next}if(endAnchor&&ordered.length>2){let rev=[...ordered].reverse(),s1=await dist(startAnchor||ordered[0],ordered[0])+await dist(ordered[ordered.length-1],endAnchor),s2=await dist(startAnchor||rev[0],rev[0])+await dist(rev[rev.length-1],endAnchor);if(s2<s1)ordered=rev}return ordered}
async function dccV31OptimizeFlexRideOrder(day){let items=itinerary[day]?.items||[],pts=await resolveDayPoints(day),byIndex=new Map(pts.map(p=>[p.index,p]));let candidate=i=>{let p=byIndex.get(i),it=items[i];return !!(p&&p.entityType==='ATTRACTION'&&dccV31OriginalFlexName(day,it?.[2]))};let groups=[];for(let i=0;i<items.length;){if(!candidate(i)){i++;continue}let s=i,a=[];while(i<items.length&&candidate(i)){a.push(i);i++}if(a.length>1)groups.push({s,e:i-1,idx:a})}if(!groups.length)return{changed:false,groups:0,before:[],after:[]};let cache=new Map(),summary=[];
 for(let gi=groups.length-1;gi>=0;gi--){let g=groups[gi],entries=g.idx.map(i=>({...byIndex.get(i),item:items[i],oldIndex:i}));let start=null,end=null;for(let i=g.s-1;i>=0;i--){if(byIndex.get(i)){start=byIndex.get(i);break}}for(let i=g.e+1;i<items.length;i++){if(byIndex.get(i)){end=byIndex.get(i);break}}let best=await dccV31BestOrder(entries,start,end,cache),oldNames=entries.map(x=>x.name),newNames=best.map(x=>x.name);if(oldNames.join('|')!==newNames.join('|')){items.splice(g.s,g.idx.length,...best.map(x=>x.item));summary.push({old:oldNames,new:newNames,start:start?.name||'',end:end?.name||''})}}
 return{changed:summary.length>0,groups:groups.length,summary}}

dccV30RecommendFlex=async function(day){
 dccV30PlannerMessage(day,'Checking the mapped walking paths first so the ride order does not backtrack…');
 let opt;try{opt=await dccV31OptimizeFlexRideOrder(day)}catch(e){opt={changed:false,summary:[]}}
 if(opt?.changed){dccSaveEditedDay(day);dayPanel(day);dccRefreshAfterItineraryEdit(day);await new Promise(r=>setTimeout(r,80))}
 await dccV31BaseRecommendFlex(day);
 if(opt?.changed)setTimeout(()=>{let x=document.getElementById('dccPlannerResult');if(!x)return;let route=opt.summary.map(s=>'• '+s.new.join(' → ')).join('<br>');x.innerHTML='<b>Walking order optimized first:</b><br>'+route+'<br><br>'+x.innerHTML+'<br><br><small>The optimizer keeps fixed reservations/shows in place and only reorders FLEX attraction blocks. It uses mapped walking-path distance, not just the order the rides were originally typed.</small>';x.classList.add('ok')},100)
};
const dccV31BaseDayPanel=dayPanel;
dayPanel=function(day){dccV31BaseDayPanel(day);setTimeout(()=>{let b=document.getElementById('dccFlexTimeBtn');if(b)b.textContent='🗺️ Optimize Route + FLEX Times';let r=document.getElementById('dccPlannerResult');if(r&&!r.dataset.v31){r.dataset.v31='1';r.innerHTML='This first optimizes FLEX ride order by mapped walking paths to reduce backtracking, then recommends times around your fixed reservations, shows, and the previous/next itinerary stops.'}},0)};
