/* DCC v34 — visual rebuild of detail tabs + location-photo day banners */
const dccV34Img={
 castle:'https://www.dein-dlrp.de/fileadmin/walt-disney-world-bilder/magic-kingdom/fantasyland/attraktionen/cinderella-castle/cinderella-castle-9.jpg',
 epcot:'https://i2.wp.com/www.piratesandprincesses.net/wp-content/uploads/2021/06/Epcot-Spaceship-Earth-Fountain-Leave-a-Legacy.jpg?resize=1920%2C1282&ssl=1',
 ak:'https://parade.com/.image/ODowMDAwMDAwMDAwNzkwMTEy/orlando-exteriors-and-landmarks-2022.jpg?profile=w2560&x=50&y=50',
 hs:'https://gd-disneyeorlando.sfo2.cdn.digitaloceanspaces.com/2015/07/hollywood-studios-disney.jpg',
 jollywood:'https://mickeyblog.com/wp-content/uploads/2024/09/Hollywood-Studios-Jollywood-Nights-2023-Decorations-Christmas-Trees-Holidays-1.jpg',
 saratoga:'https://cache.undercovertourist.com/blog/2024/10/1024-saratoga-springs-exterior.jpg',
 wyndham:'https://symphony.cdn.tambourine.com/wyndham-grand-bonnet-creek/media/wgorbc-gallery-04-5d5588d16efec.jpg',
 skyliner:'https://i0.wp.com/www.disneytouristblog.com/wp-content/uploads/2019/09/skyliner-gondolas-disney-world-aerial-transportation-294.jpg?resize=800%2C539&ssl=1',
 plane:'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1600&q=82',
 dining:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=82',
 map:'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1600&q=82'
};
function dccV34SafeImg(url){return '<img src="'+dccEsc(url)+'" alt="" loading="lazy" onerror="this.onerror=null;this.src=\'/disney-command-center/castle-hero.jpg\'">'}
function dccV34MapHref(name){return 'https://maps.apple.com/?q='+encodeURIComponent(name+' Walt Disney World Florida')}
function dccV34RouteHref(name){return 'https://maps.apple.com/?daddr='+encodeURIComponent(name+' Walt Disney World Florida')}
function dccV34Badge(x,cls=''){return '<span class="dccBadge '+cls+'">'+dccEsc(x)+'</span>'}
function dccV34Action(a){if(a.day)return '<button type="button" '+(a.primary?'class="primary"':'')+' data-day="'+dccEsc(a.day)+'">'+dccEsc(a.label)+'</button>';if(a.open)return '<button type="button" '+(a.primary?'class="primary"':'')+' data-open="'+dccEsc(a.open)+'">'+dccEsc(a.label)+'</button>';return '<a '+(a.primary?'class="primary"':a.gold?'class="gold"':'')+' target="_blank" rel="noopener" href="'+dccEsc(a.href)+'">'+dccEsc(a.label)+'</a>'}
function dccV34Hero(title,sub,img,ey='Disney Command Center'){return '<div class="dccVisualHero">'+dccV34SafeImg(img)+'<div class="dccSparkle">✨ Disney 2026</div><div class="dccVisualHeroText"><div class="dccVisualEyebrow">'+dccEsc(ey)+'</div><h2>'+dccEsc(title)+'</h2><p>'+dccEsc(sub)+'</p></div></div>'}
function dccV34Card(o){let badges=(o.badges||[]).map((b,i)=>dccV34Badge(typeof b==='string'?b:b.text,typeof b==='string'?'':(b.cls||''))).join(''),meta=(o.meta||[]).map(x=>'<div class="dccMetaBox"><small>'+dccEsc(x[0])+'</small><b>'+dccEsc(x[1])+'</b></div>').join(''),acts=(o.actions||[]).map(dccV34Action).join('');return '<article class="dccVisualCard">'+(o.img?'<div class="dccVisualCardImg">'+dccV34SafeImg(o.img)+(badges?'<div class="dccVisualBadgeRow">'+badges+'</div>':'')+'</div>':'')+'<div class="dccVisualBody"><h3>'+dccEsc(o.title)+'</h3>'+(o.sub?'<div class="dccVisualSub">'+dccEsc(o.sub)+'</div>':'')+(meta?'<div class="dccVisualMeta">'+meta+'</div>':'')+(o.note?'<div class="dccVisualNote">'+dccEsc(o.note)+'</div>':'')+(acts?'<div class="dccVisualActions">'+acts+'</div>':'')+'</div></article>'}
function dccV34Open(title,html){$('pt').textContent=title;$('pb').innerHTML='<div class="dccVisualPanel">'+html+'</div>';$('panel').classList.add('open')}
function dccV34Hotels(){let h=dccV34Hero('Your Disney-area stays','Two resorts, two different trip phases — arrival weekend and the Disney resort portion.',dccV34Img.saratoga,'Stay & recharge');h+='<div class="dccVisualGrid">';h+=dccV34Card({img:dccV34Img.wyndham,title:'Wyndham Grand Orlando Resort Bonnet Creek',sub:'Arrival stay • Nov 27–29',badges:[{text:'Nov 27–29',cls:'gold'},'Arrival hotel'],meta:[['AREA','Bonnet Creek'],['PLAN','Check in + easy first night']],note:'Use this as the low-stress arrival base before Jollywood Nights.',actions:[{label:'📍 View Map',href:dccV34MapHref('Wyndham Grand Orlando Resort Bonnet Creek')},{label:'🧭 Route There',href:dccV34RouteHref('Wyndham Grand Orlando Resort Bonnet Creek'),primary:true},{label:'Hotel Website',href:'https://www.wyndhamgrandorlando.com/'}]});h+=dccV34Card({img:dccV34Img.saratoga,title:"Disney’s Saratoga Springs Resort & Spa",sub:'Disney resort stay • Nov 29–Dec 5',badges:[{text:'Nov 29–Dec 5',cls:'gold'},{text:'Check-in complete',cls:'green'}],meta:[['AREA','Disney Springs Resort Area'],['BEST FEATURE','Walk / boat to Disney Springs']],note:'Your main Disney home base. The planner uses Saratoga for return-to-hotel timing and transportation decisions.',actions:[{label:'🗺️ Resort Map',href:'https://disneyworld.disney.go.com/media/wdw_nextgen/CoreCatalog/WaltDisneyWorld/en_us/Media/InternetMediaType/Resorts/SaratogaSprings/saratoga-springs-map.pdf'},{label:'🧭 Route There',href:dccV34RouteHref("Disney's Saratoga Springs Resort & Spa"),primary:true},{label:'Disney Resort Page',href:'https://disneyworld.disney.go.com/resorts/saratoga-springs-resort-and-spa/'}]});return h+'</div>'}
function dccV34Flights(){let h=dccV34Hero('Flights','Your outbound and return flights with the information you’ll want at a glance.',dccV34Img.plane,'Travel day');h+='<div class="dccVisualGrid">';for(const [num,f] of Object.entries(dccV30Flights||{})){h+=dccV34Card({img:dccV34Img.plane,title:num+' • '+f.route,sub:f.date,badges:[{text:'✈️ '+f.depart,cls:'gold'},'Seats saved'],meta:[['DEPART',f.depart+' • '+f.from],['ARRIVE',f.arrive+' • '+f.to],['SEAT 1',f.seats[0][0]+' • '+f.seats[0][1]],['SEAT 2',f.seats[1][0]+' • '+f.seats[1][1]]],note:'Flight times are your current planning baseline; gate and terminal can be added when available.',actions:[{label:'🗺️ Departure Airport',href:dccV34MapHref(f.from+' airport')},{label:'View travel day',day:num==='AA 1697'?'2026-11-27':'2026-12-05',primary:true}]})}return h+'</div>'}
function dccV34Dining(){let h=dccV34Hero('Dining plans','Reservations, meal candidates and food stops organized around your park route.',dccV34Img.dining,'Eat without backtracking'),rows=[];for(const [day,v] of Object.entries(itinerary)){for(const x of v.items){if(/restaurant|dinner|lunch|breakfast|brunch|meal|cake bake|yak & yeti|via napoli|le cellier|brown derby|turf club|bakery/i.test(x[2]+' '+x[3]))rows.push({day,v,x})}}h+='<div class="dccVisualGrid">';for(const r of rows){h+=dccV34Card({img:dccV34Img.dining,title:r.x[2],sub:r.v.title+' • '+(r.x[0]?fmt(r.x[0]):'FLEX'),badges:[r.x[0]?{text:fmt(r.x[0]),cls:'gold'}:'FLEX','Dining'],meta:[['DAY',r.v.title],['LOCATION',r.v.sub]],note:r.x[3],actions:[{label:'📍 Map',href:dccV34MapHref(r.x[2])},{label:'Open day',day:r.day,primary:true}]})}if(!rows.length)h+='<div class="dccVisualEmpty">No dining items are planned yet.</div>';return h+'</div>'}
function dccV34Travel(){let h=dccV34Hero('Getting around Disney','Walking, boats, Skyliner, buses and rideshare — the planner compares the fastest practical choice.',dccV34Img.skyliner,'Best route');h+='<div class="dccVisualGrid">';h+=dccV34Card({img:dccV34Img.skyliner,title:'EPCOT ↔ Hollywood Studios',sub:'Skyliner or walking/boat connections',badges:['Skyliner',{text:'Park hop',cls:'purple'}],meta:[['ROUTE','International Gateway → Skyliner'],['USE WHEN','Moving between EPCOT + Studios']],note:'The route planner compares the transfer time with where you are and your next timed anchor.',actions:[{label:'Open Dec 3',day:'2026-12-03',primary:true},{label:'Disney Skyliner',href:'https://disneyworld.disney.go.com/skyliner/'}]});h+=dccV34Card({img:dccV34Img.hs,title:'BoardWalk → Hollywood Studios',sub:'Walk or Friendship Boat',badges:['Walk / Boat',{text:'Nov 28',cls:'gold'}],meta:[['WALK','~25–30 min family pace'],['BOAT','Best if one is boarding soon']],note:'The app should favor the option that gets you there fastest while saving feet before Jollywood.',actions:[{label:'Open Jollywood day',day:'2026-11-28',primary:true},{label:'Map BoardWalk',href:dccV34MapHref("Disney's BoardWalk")}]});h+=dccV34Card({img:dccV34Img.saratoga,title:'Saratoga Springs ↔ Disney Springs',sub:'Walkway, boat or bus depending resort section',badges:['Resort route',{text:'Low stress',cls:'green'}],meta:[['BEST CASE','Walk from Congress Park'],['ALTERNATE','Boat / bus']],note:'Your Saratoga map and resort section matter here; once room location is known the app can tighten this route.',actions:[{label:'Open Nov 29',day:'2026-11-29',primary:true},{label:'Resort Map',href:'https://disneyworld.disney.go.com/media/wdw_nextgen/CoreCatalog/WaltDisneyWorld/en_us/Media/InternetMediaType/Resorts/SaratogaSprings/saratoga-springs-map.pdf'}]});return h+'</div>'}
function dccV34Parties(){let h=dccV34Hero('Holiday party nights','Your two special-ticket nights deserve their own visual plan.',dccV34Img.jollywood,'Holiday magic');h+='<div class="dccVisualGrid">';h+=dccV34Card({img:dccV34Img.jollywood,title:'Disney Jollywood Nights',sub:'Hollywood Studios • Nov 28',badges:[{text:'5:30 PM entry',cls:'gold'},{text:'7:30 PM party',cls:'purple'}],meta:[['ANCHOR','Fantasmic! • 6:30 PM'],['ENDS','12:30 AM']],note:'Prioritize party-only shows and character experiences before rides you can do on another Studios day.',actions:[{label:'Open full plan',day:'2026-11-28',primary:true},{label:'Official Event Page',href:'https://disneyworld.disney.go.com/events-tours/hollywood-studios/jollywood-nights/'}]});h+=dccV34Card({img:dccV34Img.castle,title:"Mickey’s Very Merry Christmas Party",sub:'Magic Kingdom • Dec 1',badges:[{text:'4:00 PM entry',cls:'gold'},{text:'7:00 PM party',cls:'purple'}],meta:[['PARK','Magic Kingdom'],['PLAN','Light afternoon → party priorities']],note:'Keep pre-party walking lighter so the family still has energy for the event window.',actions:[{label:'Open party plan',day:'2026-12-01',primary:true},{label:'Magic Kingdom Map',href:dccV34MapHref('Magic Kingdom Walt Disney World')}]});return h+'</div>'}
function dccV34Lightning(){let h=dccV34Hero('Lightning Lane strategy','Keep high-value selections visible without letting them wreck the walking route.',dccV34Img.epcot,'Priority windows'),rows=[];for(const [day,v] of Object.entries(itinerary)){for(const x of v.items){if(/lightning|LL idea|single pass|priority/i.test(x[3])&&/ride|pass|priority|LL/i.test(x[3]+' '+x[2]))rows.push({day,v,x})}}h+='<div class="dccMiniList">';for(const r of rows.slice(0,18))h+='<div class="dccMiniCard"><div class="dccMiniIcon">'+r.x[1]+'</div><div><b>'+dccEsc(r.x[2])+'</b><small>'+dccEsc(r.v.title)+' • '+dccEsc(r.x[3])+'</small></div><div class="dccMiniTime">'+(r.x[0]?dccEsc(fmt(r.x[0])):'FLEX')+'</div></div>';if(!rows.length)h+='<div class="dccVisualEmpty">Lightning Lane windows can be added as timed anchors when booked.</div>';return h+'</div>'}
function dccV34Conditions(){let weather=$('weather')?.textContent||'Loading…',rides=$('rideops')?.textContent||'Loading…',crowd=$('crowd')?.textContent||'Loading…';let h=dccV34Hero('Live conditions','Weather, ride operations and wait pressure in one place.',dccV34Img.castle,'Right now');h+='<div class="dccVisualGrid">';h+=dccV34Card({img:dccV34Img.castle,title:'Orlando weather',sub:weather,badges:['Live conditions'],meta:[['WEATHER',weather],['REFRESH','Automatic']],note:'Use this with your day plan for rain timing, indoor breaks and transportation choices.',actions:[{label:'Weather details',href:'https://weather.com/weather/today/l/Orlando+FL',primary:true}]});h+=dccV34Card({img:dccV34Img.hs,title:'Ride operations',sub:rides,badges:['Live rides'],meta:[['STATUS',rides],['WAIT PRESSURE',crowd]],note:'The live map remains the best place to compare attraction waits by exact location.',actions:[{label:'Open Live Map',href:'#',primary:true}]});return h+'</div>'}
function dccV34Trip(){let h=dccV34Hero('Your trip at a glance','Tap any day to open its itinerary, map, planner and edit controls.',dccV34Img.castle,'Nov 27 – Dec 5');h+='<div class="dccVisualGrid">';for(const [day,v] of Object.entries(itinerary)){let img=dccV34DayImage(day);h+=dccV34Card({img,title:v.title,sub:v.sub,badges:[new Date(day+'T12:00:00').toLocaleDateString([],{month:'short',day:'numeric'})],actions:[{label:'Open day',day,primary:true}]})}return h+'</div>'}
function dccV34Recommend(){let h=dccV34Hero('Disney Travel Planner','Open a day and use the built-in planner for the best next ride, lunch, route, characters or when to head back.',dccV34Img.map,'Smart recommendations');h+='<div class="dccSectionLabel">Quick planning days</div><div class="dccVisualGrid">';for(const day of Object.keys(itinerary).filter(d=>day>='2026-11-28'&&day<='2026-12-04')){let v=itinerary[day];h+=dccV34Card({img:dccV34DayImage(day),title:v.title,sub:v.sub,badges:['Map-aware','Live waits on trip day'],note:'Open the day → Edit → Disney Travel Planner for 1–3 ranked choices.',actions:[{label:'Open planner day',day,primary:true}]})}return h+'</div>'}
function dccV34Today(){let day=typeof activeMapDay==='function'?activeMapDay():Object.keys(itinerary)[0],v=itinerary[day];return dccV34Hero('Next trip focus',v?v.title:'Disney 2026',dccV34DayImage(day),'Today / next up')+(v?dccV34Card({img:dccV34DayImage(day),title:v.title,sub:v.sub,badges:['Next focus'],actions:[{label:'Open day',day,primary:true},{label:'Open map',href:'#'}]}):'')}
const dccV34OldGeneric=generic;
generic=function(k){if(k==='hotels')return dccV34Open('Hotels',dccV34Hotels());if(k==='flights')return dccV34Open('Flights',dccV34Flights());if(k==='dining')return dccV34Open('Dining',dccV34Dining());if(k==='travel')return dccV34Open('Travel',dccV34Travel());if(k==='parties')return dccV34Open('Parties',dccV34Parties());if(k==='lightning')return dccV34Open('Lightning',dccV34Lightning());if(k==='conditions')return dccV34Open('Live Conditions',dccV34Conditions());if(k==='trip')return dccV34Open('My Trip',dccV34Trip());if(k==='recommend')return dccV34Open('Recommendations',dccV34Recommend());if(k==='today')return dccV34Open('Today',dccV34Today());return dccV34OldGeneric(k)};
function dccV34DayImage(day){if(day==='2026-11-27'||day==='2026-12-05')return dccV34Img.plane;if(day==='2026-11-28')return dccV34Img.jollywood;if(day==='2026-11-29')return dccV34Img.saratoga;if(day==='2026-11-30')return dccV34Img.ak;if(day==='2026-12-01'||day==='2026-12-04')return dccV34Img.castle;if(day==='2026-12-02')return dccV34Img.epcot;if(day==='2026-12-03')return dccV34Img.hs;return dccV34Img.castle}
function dccV34DecorateDay(day){let pb=$('pb');if(!pb||pb.querySelector('.dccDayHero'))return;let v=itinerary[day];if(!v)return;let box=document.createElement('div');box.className='dccDayHero';box.innerHTML=dccV34SafeImg(dccV34DayImage(day))+'<div class="dccDayHeroTag">✨ Disney 2026</div><div class="dccDayHeroText"><span>'+new Date(day+'T12:00:00').toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})+'</span><b>'+dccEsc(v.title)+'</b><small>'+dccEsc(v.sub)+'</small></div>';pb.prepend(box)}
const dccV34BaseDayPanel=dayPanel;
dayPanel=function(day){dccV34BaseDayPanel(day);setTimeout(()=>dccV34DecorateDay(day),0)};
/* Make card links that intentionally point to # open the live map instead of navigating. */
document.addEventListener('click',e=>{let a=e.target.closest('.dccVisualActions a[href="#"]');if(!a)return;e.preventDefault();if(typeof dccOpenLiveAllParks==='function')dccOpenLiveAllParks();else if(typeof openLiveMap==='function')openLiveMap()});
