function miles(a,b){const R=3958.8,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p,x=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function placeStatic(name){let n=nrm(name);for(const [k,lat,lon,label] of staticPlaces)if(n.includes(k))return{lat,lon,label,source:'known'};return null}
function likelyPlace(name){let n=nrm(name);return /(restaurant|bakery|resort|hotel|springs|boardwalk|kingdom|epcot|studios|airport|ride|safari|everest|remy|soarin|frozen|nemo|track|spaceship|living|pirates|haunted|dumbo|peter pan|jungle|small world|tiana|mermaid|pooh|buzz|mine train|runaway|rise|toy story|slinky|fantasmic|villains|indiana|philharmagic|tiki|yak yeti|sir mickey|skyliner)/.test(n)}
const parkAliases={
'nightmare before christmas show':'the nightmare before christmas sing along','the nightmare before christmas sing along':'the nightmare before christmas sing along','rise of the resistance':'star wars rise of the resistance','star wars rise of the resistance':'star wars rise of the resistance','toy story mania':'toy story mania','mickey minnie s runaway railway':'mickey minnie s runaway railway','flight of passage':'avatar flight of passage','avatar flight of passage':'avatar flight of passage','finding nemo show':'finding nemo the big blue and beyond','finding nemo the big blue and beyond':'finding nemo the big blue and beyond','soarin':'soarin around the world','soarin around the world':'soarin around the world','little mermaid musical adventure':'the little mermaid a musical adventure','the little mermaid a musical adventure':'the little mermaid a musical adventure','indiana jones':'indiana jones epic stunt spectacular','indiana jones epic stunt spectacular':'indiana jones epic stunt spectacular','frozen sing along':'for the first time in forever a frozen sing along celebration','for the first time in forever a frozen sing along celebration':'for the first time in forever a frozen sing along celebration','villains show':'disney villains unfairly ever after','disney villains unfairly ever after':'disney villains unfairly ever after','expedition everest':'expedition everest legend of the forbidden mountain','monsters inc laugh floor':'monsters inc laugh floor','under the sea journey of the little mermaid':'under the sea journey of the little mermaid','winnie the pooh':'the many adventures of winnie the pooh','the many adventures of winnie the pooh':'the many adventures of winnie the pooh','buzz lightyear s space ranger spin':'buzz lightyear s space ranger spin','mickey s philharmagic':'mickey s philharmagic','enchanted tiki room':'walt disney s enchanted tiki room','walt disney s enchanted tiki room':'walt disney s enchanted tiki room','tiana s bayou adventure':'tiana s bayou adventure','seven dwarfs mine train':'seven dwarfs mine train','peter pan s flight':'peter pan s flight','it s a small world':'it s a small world','pirates of the caribbean':'pirates of the caribbean','haunted mansion':'haunted mansion','dumbo':'dumbo the flying elephant','dumbo the flying elephant':'dumbo the flying elephant','jungle cruise':'jungle cruise','frozen ever after':'frozen ever after','test track':'test track','remy s ratatouille adventure':'remy s ratatouille adventure','spaceship earth':'spaceship earth','living with the land':'living with the land','the seas with nemo friends':'the seas with nemo friends','kilimanjaro safaris':'kilimanjaro safaris','festival of the lion king':'festival of the lion king','wildlife express train':'wildlife express train','kali river rapids':'kali river rapids','na vi river journey':'na vi river journey','slinky dog dash':'slinky dog dash','fantasmic':'fantasmic'};
function canonName(name){let n=nrm(name);return parkAliases[n]||n}
async function geocodePlace(name){const key='dcc-geo-'+nrm(name).slice(0,80);try{let c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Number.isFinite(c.lat))return c}catch(e){}if(!likelyPlace(name))return null;try{let q=encodeURIComponent(name+' Walt Disney World Florida'),r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+q,{headers:{'Accept':'application/json'}}),j=await r.json();if(j&&j[0]){let c={lat:+j[0].lat,lon:+j[0].lon,label:j[0].display_name.split(',').slice(0,2).join(','),source:'OpenStreetMap'};localStorage.setItem(key,JSON.stringify(c));return c}}catch(e){}return null}
async function parkLocations(day){let map=new Map(),keys=dayParkKeys[day]||[];await Promise.all(keys.map(async k=>{try{let j=await live(P[k].id);for(const x of j.liveData||[]){let loc=x.location;if(loc&&Number.isFinite(loc.latitude)&&Number.isFinite(loc.longitude)){let v={lat:loc.latitude,lon:loc.longitude,label:x.name,source:P[k].n,entityType:x.entityType};map.set(nrm(x.name),v);map.set(canonName(x.name),v)}}}catch(e){}}));return map}
function fuzzyPark(name,pmap){let n=canonName(name),direct=pmap.get(n);if(direct)return direct;let a=n.split(' ').filter(w=>w.length>1),best=null,bestScore=0;for(const [k,v] of pmap){let ck=canonName(k),b=ck.split(' ').filter(w=>w.length>1),same=a.filter(w=>b.includes(w)).length,union=new Set([...a,...b]).size,score=union?same/union:0;if(ck.includes(n)||n.includes(ck))score=Math.max(score,.78);if(score>bestScore){bestScore=score;best=v}}return bestScore>=.34?best:null}
async function resolveDayPoints(day){let pmap=await parkLocations(day),raw=(itinerary[day]?.items||[]).map((x,i)=>({index:i,time:x[0],icon:x[1],name:x[2],note:x[3]})),out=[];for(const it of raw){let p=placeStatic(it.name)||fuzzyPark(it.name,pmap);if(!p&&likelyPlace(it.name))p=await geocodePlace(it.name);if(!p){let keys=dayParkKeys[day]||[],low=nrm(it.name);if(keys.length===1&&(low.includes('entry')||low.includes('party')||low.includes('exit')))p={lat:P[keys[0]].c[0],lon:P[keys[0]].c[1],label:P[keys[0]].n,source:'park center'}}if(p)out.push({...it,...p})}return out}
const manualLegHints={
'2026-11-28':{"The Cake Bake Shop|Disney's Hollywood Studios":['Walk / Friendship boat','25–30 min family-paced walk; boat can be similar once waiting is included'],"Disney's Hollywood Studios|Disney Jollywood Nights entry":['Walk','5–10 min from arrival area to event entry']},
'2026-11-29':{"Disney's Saratoga Springs Resort & Spa|Summer House on the Lake":['Walk / boat','About 10–25 min depending your Saratoga section and boat timing']},
'2026-12-03':{'EPCOT International Gateway / Skyliner|Disney Villains: Unfairly Ever After':['Skyliner + walk','Allow roughly 25–35 min from EPCOT International Gateway to inside Studios']}
};
function legMode(day,a,b,d){let key=a.name+'|'+b.name,h=manualLegHints[day]?.[key];if(h)return{mode:h[0],detail:h[1],mins:null};let text=nrm(a.name+' '+b.name);if(text.includes('uber'))return{mode:'Rideshare',detail:'Allow pickup time plus the drive',mins:Math.max(15,Math.round(d/22*60+8))};if(text.includes('skyliner'))return{mode:'Skyliner + walk',detail:'Allow station/wait and family-paced walking',mins:Math.max(20,Math.round(d/8*60+12))};if(text.includes('boat'))return{mode:'Walk / boat',detail:'Compare the next boat with the walking path',mins:Math.max(15,Math.round(d/3*60+8))};if(d<=1.25)return{mode:'Walk',detail:'Family-paced estimate with crowd buffer',mins:Math.max(4,Math.round(d*22+3))};return{mode:'Disney transport / rideshare',detail:'Road route with pickup/wait buffer; Disney buses use backstage/transport roads where public routing permits',mins:Math.max(20,Math.round(d/15*60+15))}}
function appleWalkLink(a,b){return 'https://maps.apple.com/?saddr='+a.lat+','+a.lon+'&daddr='+b.lat+','+b.lon+'&dirflg=w'}
function appleDriveLink(a,b){return 'https://maps.apple.com/?saddr='+a.lat+','+a.lon+'&daddr='+b.lat+','+b.lon+'&dirflg=d'}
async function brouterProfileLine(a,b,profile='trekking'){try{let u='https://brouter.de/brouter?lonlats='+a.lon+','+a.lat+'%7C'+b.lon+','+b.lat+'&profile='+encodeURIComponent(profile)+'&alternativeidx=0&format=geojson',r=await fetch(u),j=await r.json();if(j&&j.features&&j.features[0])return j.features[0].geometry.coordinates.map(c=>[c[1],c[0]])}catch(e){}return null}
async function brouterLine(a,b){return brouterProfileLine(a,b,'trekking')}
function friendshipBoatLine(a,b){return [[a.lat,a.lon],[28.36775,-81.55765],[28.36825,-81.55845],[28.37115,-81.55865],[28.37035,-81.55955],[28.36560,-81.56110],[28.36135,-81.56015],[28.35875,-81.55855],[b.lat,b.lon]]}
function skylinerLine(a,b){return [[a.lat,a.lon],[28.37555,-81.54955],[28.37720,-81.53925],[28.35895,-81.54355],[28.35655,-81.55835],[b.lat,b.lon]]}
async function routeLines(day,a,b,g){let mode=(g.mode||'').toLowerCase(),lines=[];if(mode.includes('friendship')||mode.includes('boat')){let walk=await brouterProfileLine(a,b,'trekking');if(walk)lines.push({kind:'walk',coords:walk});lines.push({kind:'boat',coords:friendshipBoatLine(a,b)});return lines}if(mode.includes('skyliner')){lines.push({kind:'skyliner',coords:skylinerLine(a,b)});return lines}if(mode.includes('walk')){let walk=await brouterProfileLine(a,b,'trekking');if(walk)lines.push({kind:'walk',coords:walk});return lines}let road=await brouterProfileLine(a,b,'car-fast');if(road)lines.push({kind:'road',coords:road});return lines}
function routeStyle(kind){if(kind==='walk')return{color:'#0b63ce',weight:5,opacity:.86};if(kind==='road')return{color:'#526f8d',weight:6,opacity:.8};if(kind==='boat')return{color:'#13a3b8',weight:5,opacity:.88,dashArray:'10 7'};if(kind==='skyliner')return{color:'#7456d8',weight:5,opacity:.9,dashArray:'5 6'};return{color:'#0b63ce',weight:5,opacity:.8}}
function drawRouteLines(target,lines){for(const x of lines||[])if(x.coords&&x.coords.length>1)L.polyline(x.coords,routeStyle(x.kind)).addTo(target)}
let dayMap=null,dayLayers=null;
function destroyDayMap(){if(dayMap){try{dayMap.remove()}catch(e){}dayMap=null;dayLayers=null}}