function miles(a,b){const R=3958.8,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lon-a.lon)*p,x=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function placeStatic(name){let n=nrm(name);for(const [k,lat,lon,label] of staticPlaces)if(n.includes(k))return{lat,lon,label,source:'known'};return null}
function likelyPlace(name){let n=nrm(name);return /(restaurant|bakery|resort|hotel|springs|boardwalk|kingdom|epcot|studios|airport|ride|safari|everest|remy|soarin|frozen|nemo|track|spaceship|living|pirates|haunted|dumbo|peter pan|jungle|small world|tiana|mermaid|pooh|buzz|mine train|runaway|rise|toy story|slinky)/.test(n)}
async function geocodePlace(name){const key='dcc-geo-'+nrm(name).slice(0,80);try{let c=JSON.parse(localStorage.getItem(key)||'null');if(c&&Number.isFinite(c.lat))return c}catch(e){}if(!likelyPlace(name))return null;try{let q=encodeURIComponent(name+' Walt Disney World Florida'),r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+q,{headers:{'Accept':'application/json'}}),j=await r.json();if(j&&j[0]){let c={lat:+j[0].lat,lon:+j[0].lon,label:j[0].display_name.split(',').slice(0,2).join(','),source:'OpenStreetMap'};localStorage.setItem(key,JSON.stringify(c));return c}}catch(e){}return null}
async function parkLocations(day){let map=new Map(),keys=dayParkKeys[day]||[];await Promise.all(keys.map(async k=>{try{let j=await live(P[k].id);for(const x of j.liveData||[]){let loc=x.location;if(loc&&Number.isFinite(loc.latitude)&&Number.isFinite(loc.longitude))map.set(nrm(x.name),{lat:loc.latitude,lon:loc.longitude,label:x.name,source:P[k].n})}}catch(e){}}));return map}
function fuzzyPark(name,pmap){let n=nrm(name),best=null,score=0;for(const [k,v] of pmap){let s=0;if(k===n)s=10;else if(k.includes(n)||n.includes(k))s=7;else{let a=new Set(n.split(' ')),b=k.split(' '),m=b.filter(w=>w.length>2&&a.has(w)).length;s=m}if(s>score){score=s;best=v}}return score>=2?best:null}
async function resolveDayPoints(day){let pmap=await parkLocations(day),raw=(itinerary[day]?.items||[]).map((x,i)=>({index:i,time:x[0],icon:x[1],name:x[2],note:x[3]})),out=[];for(const it of raw){let p=placeStatic(it.name)||fuzzyPark(it.name,pmap);if(!p&&likelyPlace(it.name))p=await geocodePlace(it.name);if(!p){let keys=dayParkKeys[day]||[];if(keys.length===1&&(it.name.toLowerCase().includes('entry')||it.name.toLowerCase().includes('party')||it.name.toLowerCase().includes('show')))p={lat:P[keys[0]].c[0],lon:P[keys[0]].c[1],label:P[keys[0]].n,source:'park center'}}if(p)out.push({...it,...p})}return out}
const manualLegHints={
'2026-11-28':{'The Cake Bake Shop|Boat or walking path to Hollywood Studios':['Walk / Friendship boat','25–30 min family-paced walk; boat can be similar once waiting is included'],'Boat or walking path to Hollywood Studios|Jollywood Nights entry':['Walk','5–10 min from arrival area to event entry']},
'2026-11-29':{'Uber to Disney’s Saratoga Springs Resort & Spa|Disney Springs brunch':['Walk / boat','About 10–25 min depending your Saratoga section and boat timing']},
'2026-12-03':{'Skyliner to Hollywood Studios|Villains show':['Skyliner + walk','Allow roughly 25–35 min from EPCOT International Gateway to inside Studios']}
};
function legMode(day,a,b,d){let key=a.name+'|'+b.name,h=manualLegHints[day]?.[key];if(h)return{mode:h[0],detail:h[1],mins:null};let text=nrm(a.name+' '+b.name);if(text.includes('uber'))return{mode:'Rideshare',detail:'Allow pickup time plus the drive',mins:Math.max(15,Math.round(d/22*60+8))};if(text.includes('skyliner'))return{mode:'Skyliner + walk',detail:'Allow station/wait and family-paced walking',mins:Math.max(20,Math.round(d/8*60+12))};if(text.includes('boat'))return{mode:'Walk / boat',detail:'Compare the next boat with the walking path',mins:Math.max(15,Math.round(d/3*60+8))};if(d<=1.25)return{mode:'Walk',detail:'Family-paced estimate with crowd buffer',mins:Math.max(4,Math.round(d*22+3))};return{mode:'Disney transport / rideshare',detail:'Use the day plan to avoid unnecessary transfers',mins:Math.max(20,Math.round(d/15*60+15))}}
function appleWalkLink(a,b){return 'https://maps.apple.com/?saddr='+a.lat+','+a.lon+'&daddr='+b.lat+','+b.lon+'&dirflg=w'}
async function brouterLine(a,b){try{let u='https://brouter.de/brouter?lonlats='+a.lon+','+a.lat+'%7C'+b.lon+','+b.lat+'&profile=trekking&alternativeidx=0&format=geojson',r=await fetch(u),j=await r.json();if(j&&j.features&&j.features[0])return j.features[0].geometry.coordinates.map(c=>[c[1],c[0]])}catch(e){}return null}
let dayMap=null,dayLayers=null;
function destroyDayMap(){if(dayMap){try{dayMap.remove()}catch(e){}dayMap=null;dayLayers=null}}