const PARKS={
 mk:{name:'Magic Kingdom',id:'75ea578a-adc8-4116-a54d-dccb60765ef9'},
 ep:{name:'EPCOT',id:'47f90d2c-e191-4239-a466-5892ef59a88b'},
 hs:{name:'Hollywood Studios',id:'288747d1-8b4f-4a64-867e-ea7c9b27bad8'},
 ak:{name:'Animal Kingdom',id:'1c84a229-8862-4648-9c71-378ddd2c7693'}
};
const badWords=/\b(down|closed|closure|temporarily closed|refurb|refurbishment|outage|evacuat|stoppage|delayed|malfunction|not operating|reopen|reopened)\b/i;
const wdwWords=/\b(walt disney world|disney world|magic kingdom|epcot|hollywood studios|animal kingdom|orlando|lake buena vista|bay lake)\b/i;
const nonWdwWords=/\b(disneyland|disney california adventure|california adventure|anaheim|disneyland paris|disneyland resort paris|tokyo disney|tokyo disneyland|tokyo disneysea|hong kong disney|shanghai disney|disney cruise|disneyland resort)\b/i;
const now=()=>Date.now();
const idFor=s=>Buffer.from(String(s||'')).toString('base64url').slice(0,72);
function clean(s=''){return String(s).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim()}
function tag(block,name){let m=block.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>','i'));return m?clean(m[1]):''}
async function getText(url,opts={},ms=6500){let ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{let r=await fetch(url,{...opts,signal:ac.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
async function getJson(url,opts={},ms=6500){let ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{let r=await fetch(url,{...opts,signal:ac.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function isWdwText(s=''){return wdwWords.test(s)&&!nonWdwWords.test(s)}
function parkGuess(title=''){let s=title.toLowerCase();if(s.includes('magic kingdom'))return'Magic Kingdom';if(s.includes('epcot'))return'EPCOT';if(s.includes('hollywood studios'))return'Hollywood Studios';if(s.includes('animal kingdom'))return'Animal Kingdom';return'Walt Disney World'}
async function liveAlerts(){let rows=[];await Promise.all(Object.entries(PARKS).map(async([pk,p])=>{try{let j=await getJson('https://api.themeparks.wiki/v1/entity/'+p.id+'/live',{headers:{Accept:'application/json'}},5500);for(const x of j.liveData||[]){if(x.entityType!=='ATTRACTION')continue;let st=String(x.status||'').toUpperCase();if(!['DOWN','REFURBISHMENT'].includes(st))continue;rows.push({id:'live-'+pk+'-'+idFor(x.id||x.name),kind:'live',verified:true,severity:st==='DOWN'?'urgent':'info',title:x.name,park:p.name,status:st==='DOWN'?'Temporarily down':'Refurbishment',detail:st==='DOWN'?'Walt Disney World live attraction feed currently reports this attraction down.':'Walt Disney World live attraction feed reports this attraction in refurbishment.',published:new Date().toISOString(),source:'ThemeParks.wiki • Walt Disney World',url:''})}}catch(e){}}));return rows}
function rssItems(xml,sourceLabel){let out=[];for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)){let b=m[1],title=tag(b,'title'),description=tag(b,'description'),link=tag(b,'link'),pub=tag(b,'pubDate'),src=tag(b,'source')||sourceLabel,hay=title+' '+description+' '+src;if(!title||!badWords.test(hay)||!isWdwText(hay))continue;let ts=Date.parse(pub)||0;if(ts&&now()-ts>72*3600e3)continue;out.push({id:'news-'+idFor(title+'|'+link),kind:'news',verified:false,severity:'report',title,park:parkGuess(hay),status:'Online report',detail:'Recent public report specifically matched to Walt Disney World in Orlando, Florida. Open the source for details.',published:pub||new Date().toISOString(),source:src||'Google News',url:link})}return out}
async function newsAlerts(){let q='("Walt Disney World" OR "Magic Kingdom" OR EPCOT OR "Disney Hollywood Studios" OR "Disney Animal Kingdom") (Orlando OR Florida) (ride OR attraction) (down OR closed OR closure OR refurbishment OR evacuated OR outage) -Disneyland -Anaheim -Paris -Tokyo -Shanghai -"Hong Kong" when:2d',u='https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=en-US&gl=US&ceid=US:en';try{return rssItems(await getText(u,{headers:{'User-Agent':'Mozilla/5.0 DisneyCommandCenter/1.0'}},6500),'Google News')}catch(e){return[]}}
async function redditAlerts(){let u='https://www.reddit.com/r/WaltDisneyWorld/search.json?q='+encodeURIComponent('ride down OR closed OR closure OR evacuated OR refurbishment')+'&restrict_sr=1&sort=new&t=week&limit=25';try{let j=await getJson(u,{headers:{'User-Agent':'DisneyCommandCenter/1.0 (family trip planner)'}},6500),out=[];for(const c of j?.data?.children||[]){let p=c?.data||{},title=String(p.title||''),body=String(p.selftext||''),hay=title+' '+body;if(!badWords.test(hay)||nonWdwWords.test(hay))continue;let ts=(p.created_utc||0)*1000;if(ts&&now()-ts>72*3600e3)continue;out.push({id:'reddit-'+String(p.id||idFor(title)),kind:'social',verified:false,severity:'report',title,park:parkGuess(hay),status:'Social report',detail:'Recent public post from r/WaltDisneyWorld. Treat as unverified until Walt Disney World live data confirms it.',published:ts?new Date(ts).toISOString():new Date().toISOString(),source:'Reddit • r/WaltDisneyWorld',url:p.permalink?'https://www.reddit.com'+p.permalink:''})}return out}catch(e){return[]}}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=240, stale-while-revalidate=300');res.setHeader('Content-Type','application/json; charset=utf-8');try{let [live,news,social]=await Promise.all([liveAlerts(),newsAlerts(),redditAlerts()]),all=[...live,...news,...social],seen=new Set();all=all.filter(x=>{let k=(x.title+'|'+x.source).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{let sa=a.verified?0:1,sb=b.verified?0:1;if(sa!==sb)return sa-sb;return(Date.parse(b.published)||0)-(Date.parse(a.published)||0)}).slice(0,30);res.status(200).json({ok:true,scope:'Walt Disney World Resort • Orlando, Florida only',updated:new Date().toISOString(),counts:{live:live.length,news:news.length,social:social.length,total:all.length},alerts:all,note:'Alerts are restricted to Walt Disney World Resort in Orlando, Florida. Disneyland and other Disney destinations are excluded.'})}catch(e){res.status(200).json({ok:false,scope:'Walt Disney World Resort • Orlando, Florida only',updated:new Date().toISOString(),counts:{live:0,news:0,social:0,total:0},alerts:[],note:'Alert sources temporarily unavailable.'})}};