const PARKS={
 mk:{name:'Magic Kingdom',id:'75ea578a-adc8-4116-a54d-dccb60765ef9'},
 ep:{name:'EPCOT',id:'47f90d2c-e191-4239-a466-5892ef59a88b'},
 hs:{name:'Hollywood Studios',id:'288747d1-8b4f-4a64-867e-ea7c9b27bad8'},
 ak:{name:'Animal Kingdom',id:'1c84a229-8862-4648-9c71-378ddd2c7693'}
};
const HOME_BASE="Disney's Saratoga Springs Resort & Spa";
const badWords=/\b(down|closed|closure|temporarily closed|refurb|refurbishment|outage|evacuat|stoppage|delayed|delay|malfunction|not operating|suspended|suspension|breakdown|reopen|reopened)\b/i;
const disneyWords=/\b(walt disney world|disney world|magic kingdom|epcot|hollywood studios|animal kingdom|saratoga springs|disney springs|ride|attraction)\b/i;
const transportWords=/\b(skyliner|gondola|monorail|bus|buses|boat|boats|water taxi|water transportation|ferry|ferryboat|friendship boat|transportation|transit)\b/i;
const outsideWords=/\b(disneyland|anaheim|california adventure|disneyland paris|tokyo disney|tokyo disneysea|shanghai disney|hong kong disney|disney cruise|disneyland resort)\b/i;
const wdwScope=/\b(walt disney world|disney world|magic kingdom|epcot|hollywood studios|animal kingdom|disney springs|saratoga springs|boardwalk|transportation and ticket center|ttc|contemporary resort|polynesian|grand floridian|caribbean beach|riviera resort|pop century|art of animation)\b/i;
const now=()=>Date.now();
const idFor=s=>Buffer.from(String(s||'')).toString('base64url').slice(0,72);
function clean(s=''){return String(s).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim()}
function tag(block,name){let m=block.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+name+'>','i'));return m?clean(m[1]):''}
async function getText(url,opts={},ms=6500){let ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{let r=await fetch(url,{...opts,signal:ac.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
async function getJson(url,opts={},ms=6500){let ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{let r=await fetch(url,{...opts,signal:ac.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
function parkGuess(title=''){let s=title.toLowerCase();if(s.includes('magic kingdom'))return'Magic Kingdom';if(s.includes('epcot'))return'EPCOT';if(s.includes('hollywood studios'))return'Hollywood Studios';if(s.includes('animal kingdom'))return'Animal Kingdom';if(s.includes('disney springs'))return'Disney Springs';if(s.includes('saratoga springs'))return HOME_BASE;return''}
function wdwOnly(text=''){return !outsideWords.test(text)&&wdwScope.test(text)}
function transportMode(text=''){let s=text.toLowerCase();if(/skyliner|gondola/.test(s))return'Disney Skyliner';if(/monorail/.test(s))return'Monorail';if(/friendship|water taxi|boat|ferry/.test(s))return'Boat / Ferry';if(/bus|buses/.test(s))return'Disney Bus';return'Disney Transportation'}
function saratogaImpact(text='',mode=''){let s=text.toLowerCase();if(/saratoga springs/.test(s))return'direct';if(/disney springs/.test(s)&&/boat|water|ferry|transport/.test(s))return'direct';if(mode==='Disney Bus'&&/resort|system|disney world|park/.test(s))return'possible';if(['Disney Skyliner','Monorail','Boat / Ferry'].includes(mode))return'trip';return''}
function fallbackFor(mode,impact){
 if(impact==='direct'&&mode==='Boat / Ferry')return'From Saratoga Springs, use the Congress Park pedestrian bridge to Disney Springs when practical; Disney bus or rideshare is the backup.';
 if(impact==='direct'||impact==='possible')return'Because Saratoga Springs is your home base, compare the next Disney bus with Minnie Van/rideshare; for Disney Springs, walking from Congress Park can be the best backup.';
 if(mode==='Disney Skyliner')return'If Skyliner is affected, use Friendship Boat or the EPCOT–Hollywood Studios walking path when practical; Disney may also provide replacement buses.';
 if(mode==='Monorail')return'If the monorail is affected, use Disney bus/ferry where available or Minnie Van/rideshare for a direct backup.';
 if(mode==='Boat / Ferry')return'If boat service is affected, compare the nearest walking path or Disney bus before rerouting.';
 return'Use the Disney Travel Planner to compare the fastest alternate route from your current location.';
}
async function liveAlerts(){let rows=[];await Promise.all(Object.entries(PARKS).map(async([pk,p])=>{try{let j=await getJson('https://api.themeparks.wiki/v1/entity/'+p.id+'/live',{headers:{Accept:'application/json'}},5500);for(const x of j.liveData||[]){if(x.entityType!=='ATTRACTION')continue;let st=String(x.status||'').toUpperCase();if(!['DOWN','REFURBISHMENT'].includes(st))continue;rows.push({id:'live-'+pk+'-'+idFor(x.id||x.name),category:'attraction',kind:'live',verified:true,severity:st==='DOWN'?'urgent':'info',title:x.name,park:p.name,status:st==='DOWN'?'Temporarily down':'Refurbishment',detail:st==='DOWN'?'Disney live attraction feed currently reports this attraction down.':'Disney live attraction feed reports this attraction in refurbishment.',published:new Date().toISOString(),source:'ThemeParks.wiki live',url:''})}}catch(e){}}));return rows}
function rssItems(xml,sourceLabel,category='attraction'){let out=[];for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)){let b=m[1],title=tag(b,'title'),desc=tag(b,'description'),link=tag(b,'link'),pub=tag(b,'pubDate'),src=tag(b,'source')||sourceLabel,text=title+' '+desc;if(!title||!badWords.test(text)||!wdwOnly(text))continue;if(category==='transport'&&!transportWords.test(text))continue;if(category==='attraction'&&transportWords.test(title)&&!/ride|attraction/.test(title.toLowerCase()))continue;let ts=Date.parse(pub)||0;if(ts&&now()-ts>72*3600e3)continue;let mode=category==='transport'?transportMode(text):'',impact=category==='transport'?saratogaImpact(text,mode):'';out.push({id:(category==='transport'?'transport-news-':'news-')+idFor(title+'|'+link),category,kind:'news',verified:false,severity:'report',title,park:parkGuess(text),mode,homeBaseImpact:impact,status:category==='transport'?'Transportation report':'Online report',detail:category==='transport'?('Recent public Walt Disney World transportation report. '+fallbackFor(mode,impact)):'Recent public web/news report that may affect a Walt Disney World ride or attraction. Open the source for details.',published:pub||new Date().toISOString(),source:src||'Google News',url:link})}return out}
async function newsAlerts(){let q='("Walt Disney World" OR "Disney World") (ride OR attraction) (down OR closed OR closure OR refurbishment OR evacuated OR outage) when:2d',u='https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=en-US&gl=US&ceid=US:en';try{return rssItems(await getText(u,{headers:{'User-Agent':'Mozilla/5.0 DisneyCommandCenter/1.0'}},6500),'Google News','attraction')}catch(e){return[]}}
async function transportNewsAlerts(){let q='("Walt Disney World" OR "Disney World") (Skyliner OR monorail OR bus OR boat OR ferry OR transportation) (down OR closed OR delayed OR suspended OR outage OR breakdown) when:2d',u='https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=en-US&gl=US&ceid=US:en';try{return rssItems(await getText(u,{headers:{'User-Agent':'Mozilla/5.0 DisneyCommandCenter/1.0'}},6500),'Google News','transport')}catch(e){return[]}}
async function redditAlerts(){let u='https://www.reddit.com/r/WaltDisneyWorld/search.json?q='+encodeURIComponent('ride down OR closed OR closure OR evacuated OR refurbishment')+'&restrict_sr=1&sort=new&t=week&limit=25';try{let j=await getJson(u,{headers:{'User-Agent':'DisneyCommandCenter/1.0 (family trip planner)'}},6500),out=[];for(const c of j?.data?.children||[]){let p=c?.data||{},title=String(p.title||''),body=String(p.selftext||''),text=title+' '+body;if(!badWords.test(text)||!wdwOnly(text)||transportWords.test(title))continue;let ts=(p.created_utc||0)*1000;if(ts&&now()-ts>72*3600e3)continue;out.push({id:'reddit-'+String(p.id||idFor(title)),category:'attraction',kind:'social',verified:false,severity:'report',title,park:parkGuess(text),status:'Social report',detail:'Recent public r/WaltDisneyWorld post. Treat as unverified until Disney/live data confirms it.',published:ts?new Date(ts).toISOString():new Date().toISOString(),source:'Reddit • r/WaltDisneyWorld',url:p.permalink?'https://www.reddit.com'+p.permalink:''})}return out}catch(e){return[]}}
async function transportRedditAlerts(){let u='https://www.reddit.com/r/WaltDisneyWorld/search.json?q='+encodeURIComponent('Skyliner down OR monorail down OR bus delay OR boat closed OR ferry down OR transportation delay')+'&restrict_sr=1&sort=new&t=week&limit=35';try{let j=await getJson(u,{headers:{'User-Agent':'DisneyCommandCenter/1.0 (family trip planner)'}},6500),out=[];for(const c of j?.data?.children||[]){let p=c?.data||{},title=String(p.title||''),body=String(p.selftext||''),text=title+' '+body;if(!badWords.test(text)||!transportWords.test(text)||!wdwOnly(text))continue;let ts=(p.created_utc||0)*1000;if(ts&&now()-ts>72*3600e3)continue;let mode=transportMode(text),impact=saratogaImpact(text,mode);out.push({id:'transport-reddit-'+String(p.id||idFor(title)),category:'transport',kind:'social',verified:false,severity:'report',title,park:parkGuess(text),mode,homeBaseImpact:impact,status:'Transportation social report',detail:'Recent public r/WaltDisneyWorld transportation report. Treat as unverified until Disney or multiple sources confirm it. '+fallbackFor(mode,impact),published:ts?new Date(ts).toISOString():new Date().toISOString(),source:'Reddit • r/WaltDisneyWorld',url:p.permalink?'https://www.reddit.com'+p.permalink:''})}return out}catch(e){return[]}}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','s-maxage=240, stale-while-revalidate=300');res.setHeader('Content-Type','application/json; charset=utf-8');try{let [live,news,social,transportNews,transportSocial]=await Promise.all([liveAlerts(),newsAlerts(),redditAlerts(),transportNewsAlerts(),transportRedditAlerts()]),all=[...live,...transportNews,...transportSocial,...news,...social],seen=new Set();all=all.filter(x=>{let k=(x.title+'|'+x.source).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>{let ah=a.homeBaseImpact==='direct'?0:a.homeBaseImpact==='possible'?1:2,bh=b.homeBaseImpact==='direct'?0:b.homeBaseImpact==='possible'?1:2;if(ah!==bh)return ah-bh;let sa=a.verified?0:1,sb=b.verified?0:1;if(sa!==sb)return sa-sb;return(Date.parse(b.published)||0)-(Date.parse(a.published)||0)}).slice(0,40);let transport=all.filter(x=>x.category==='transport');res.status(200).json({ok:true,updated:new Date().toISOString(),scope:'Walt Disney World Resort • Orlando, Florida only',homeBase:HOME_BASE,counts:{live:live.length,news:news.length,social:social.length,transport:transport.length,total:all.length},alerts:all,note:'Saratoga Springs transportation disruptions are prioritized. Live attraction status is separated from unverified public news/social transportation and ride reports.'})}catch(e){res.status(200).json({ok:false,updated:new Date().toISOString(),scope:'Walt Disney World Resort • Orlando, Florida only',homeBase:HOME_BASE,counts:{live:0,news:0,social:0,transport:0,total:0},alerts:[],note:'Alert sources temporarily unavailable.'})}};